var baseUrl = './images/'
var earthData = [
    {
        list:[ //欧美地区
            {
                name:'阿根廷·布宜诺斯艾利斯',
                url:baseUrl+'zhou1/1.jpg'
            },
            {
                name:'巴黎·埃菲尔铁塔',
                url:baseUrl+'zhou1/2.jpg'
            },
            {
                name:'荷兰·阿姆斯特丹',
                url:baseUrl+'zhou1/3.jpg'
            },
            {
                name:'加拿大·魁北克',
                url:baseUrl+'zhou1/4.jpg'
            },
            {
                name:'罗马·神庙',
                url:baseUrl+'zhou1/5.jpg'
            },
            {
                name:'墨西哥·坎昆',
                url:baseUrl+'zhou1/6.jpg'
            },
            {
                name:'瑞典·斯德哥尔摩市政厅',
                url:baseUrl+'zhou1/7.jpg'
            },
            {
                name:'玻利维亚·乌尤尼盐湖',
                url:baseUrl+'zhou1/8.jpg'
            },
        ]
    },
    {
        list:[ //非洲
            {
                name:'埃及·开罗',
                url:baseUrl+'zhou2/1.jpg'
            },
            {
                name:'非洲·肯尼亚',
                url:baseUrl+'zhou2/2.jpg'
            },
            {
                name:'非洲·赞比亚',
                url:baseUrl+'zhou2/3.jpg'
            },
            {
                name:'南非·开普敦',
                url:baseUrl+'zhou2/4.jpg'
            },
            {
                name:'摩洛哥·卡萨布兰卡',
                url:baseUrl+'zhou2/5.jpg'
            },
        ]
    },
    {
        list:[ //亚洲地区
            {
                name:'柬埔寨·暹粒',
                url:baseUrl+'zhou3/1.jpg'
            },
            {
                name:'日本·东京',
                url:baseUrl+'zhou3/2.jpg'
            },
            {
                name:'新加坡',
                url:baseUrl+'zhou3/3.jpg'
            },
            {
                name:'亚洲·不丹',
                url:baseUrl+'zhou3/4.jpg'
            },
            {
                name:'印度尼西亚·巴厘岛',
                url:baseUrl+'zhou3/5.jpg'
            },
            {
                name:'中国·澳门',
                url:baseUrl+'zhou3/6.jpg'
            },
            {
                name:'中国·台湾',
                url:baseUrl+'zhou3/7.jpg'
            },
            {
                name:'中国·香港',
                url:baseUrl+'zhou3/8.jpg'
            },
        ]
    },
    {
        list:[ //大洋洲
            {
                name:'新西兰奥克兰',
                url:baseUrl+'zhou4/1.jpg'
            },
            {
                name:'澳大利亚·布里斯班',
                url:baseUrl+'zhou4/2.jpg'
            },
            {
                name:'澳大利亚·凯恩斯',
                url:baseUrl+'zhou4/3.jpg'
            },
            {
                name:'澳大利亚·悉尼',
                url:baseUrl+'zhou4/4.jpg'
            }
        ]
    },
]

var slogan = [
    {
        id:0,
        txt:'趁年轻，早出发',
        url:baseUrl+'slogan/1.png'
    },
    {
        id:1,
        txt:'没有时间是借口，抵达远方才是成功',
        url:baseUrl+'slogan/2.png'
    },
    {
        id:2,
        txt:'看世界，看见不一样的自己',
        url:baseUrl+'slogan/3.png'
    },
    {
        id:3,
        txt:'沿途遇到的风景，人生最好的邂逅',
        url:baseUrl+'slogan/4.png'
    },
    {
        id:4,
        txt:'梦里反复出现的场景，这一刻就在眼前',
        url:baseUrl+'slogan/5.png'
    },
    {
        id:5,
        txt:'一个人旅行也很好，难得的时光，和自己独处',
        url:baseUrl+'slogan/6.png'
    },
    {
        id:6,
        txt:'你那么努力，配得上这么美好的旅行',
        url:baseUrl+'slogan/7.png'
    },
    {
        id:7,
        txt:'昨天我们决定，明年我们要一起去巴黎',
        url:baseUrl+'slogan/8.png'
    },
    {
        id:8,
        txt:'曾经说好的环岛旅行，如今终于成行',
        url:baseUrl+'slogan/9.png'
    },
    {
        id:9,
        txt:'去更多地方，看更多美景',
        url:baseUrl+'slogan/10.png'
    }
]